inventory:
  service:
    url: http://localhost:8082
loki:
  url: http://localhost:3100/loki/api/v1/push
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: order-service
  tracing:
    sampling:
      probability: 1.0
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        event-consumer-buffer-size: 10
        failureRateThreshold: 50
        minimum-number-of-calls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/order_service
    username: root
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8085
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic: order-placed
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html